### ISSUE TITLE
Question about discrepancy with ProGen2 paper results on indel datasets

### ISSUE THREAD

**Issue by timt51** [OATML-Markslab/Tranception#10]
Hi!

I noticed that there is a discrepancy between the spearman correlations on the indel datasets for ProGen2 recorded in this repo and in the ProGen2 paper https://arxiv.org/pdf/2206.13517.pdf (Table 6). Any idea what might be the cause of the difference?

Thanks!

**Comment by pascalnotin** [comment]
Hi,

There seems to be two errors in the Progen2 paper:

1. In Table 6, the signs of reported spearman correlations appear to have been ignored. When replicating results with the Progen2 open source codebase, we find this is an issue for the protein CAPSD_AAV2S for which the spearman correlations are negative for Progen2 S, Progen2 M, Progen2 Base and Progen2 L (it is positive for Progen2 XL). Note that when curating assays in ProteinGym, we made sure to standardize things across assays so that higher DMS scores always equate to higher fitness. A negative spearman thus indicates a model that is worse than random predictions. Progen2 models perform relatively well on other indel assays, but the conclusion drawn under Table 6 seems incorrect (no Progen2 variant outperforms any of the other models listed in that table). You can see the DMS-level results we obtain for all baselines [here](https://www.proteingym.org/indels-dms-level).

2. Table 2 is incorrect as well. The assays from Hesselow et al. (first arxiv version) that were used to compute the reported Progen2 spearmans in that table a) did not contain multiple mutants b) were processed differently from assays in ProteinGym (eg., we removed silent mutation, duplicates, etc in ProteinGym). As a result, this table compares spearmans obtained on relatively different sets of mutations across models which is misleading. When computing performance on consistent sets of mutants, we obtain very different results -- whether you consider all 87 substitution assays in ProteinGym, or the subset of 40 we had in the first version of Hesselow et al. (we since updated results in the second arxiv version of that paper with all 87 substitution assays in ProteinGym). Results on the full ProteinGym substitution benchmark are available [here](https://www.proteingym.org/substitutions). For example, none of the Progen2 variants appear to do better than MSA Transformer, ESM-1v or Tranception (with or without retrieval).

**Comment by timt51** [comment]
Got it, that makes sense. Thanks for investigating!
