### ISSUE TITLE
How should I use the class MSA_processing to generate new MSA weight files?

### ISSUE THREAD

**Issue by NOforgetQY** [OATML-Markslab/Tranception#11]
Hi！Thank you so much for all your efforts!
I have a new protein MSA file( .a2m) by jackhmmer, but I don't know how to use the class MSA_processing to generate a new MSA weight files like the(.npy)files under the MSA_weights folder.
Would you be willing to provide some sample code, thank you very much!

**Comment by pascalnotin** [comment]
Hi - thank you for the kind words!

The weight computation is analogous to the one we used in the EVE codebase. You may use the following script up to line 43 to compute and save weights for a new MSA at the specified location: https://github.com/OATML-Markslab/EVE/blob/master/train_VAE.py#L38
Regarding the theta value used to compute these weights, we follow Hopf et al. [1] and use theta = 0.01 for viruses and 0.2 otherwise.
The weights computation fully takes place on CPU, and the time complexity depends on both the sequence length and the number of sequences in the MSA.

Best,
Pascal

[1] Hopf, T.A., Ingraham, J., Poelwijk, F.J., Schärfe, C.P., Springer, M., Sander, C., & Marks, D.S. (2017). Mutation effects predicted from sequence co-variation. Nature Biotechnology, 35, 128-135.

**Comment by NOforgetQY** [comment]
> 

Thank you very much for your reply. The answer is the same as my previous guess, but I did not specify the value of theta and use_ Weightts is also set to False, so I always run with errors that I suspect I've found the wrong way to use it. Now that I'm done, thank you again.
