### ISSUE TITLE
DMS directionality

### ISSUE THREAD

**Issue by rmrao** [OATML-Markslab/Tranception#2]
Hi all - awesome work on the paper, and really great data release.

I noticed in your README you say that in the processed data, higher DMS score -> higher fitness. This implies to me that for all DMS scores, correlations should be positive.  However when I ran the data myself I don't get that.

E.g. on `BLAT_ECOLX_Deng_2012`, the reference file says the `raw_DMS_directionality = -1`, so I do expect a negative correlation using the raw scores. But the raw scores and the processed scores are the same, so I get a negative correlation there too.

Would be great if these were either pre-negated or if you just remove the `raw_` prefix from the `raw_DMS_directionality` label, if it's true for both raw and processed.

**Comment by pascalnotin** [comment]
Dear Roshan,

Thank you for the feedback! Your understanding is correct: for `BLAT_ECOLX_Deng_2012`, the expected behavior should be a negative correlation between model predictions and the raw experimental measurements (as indicated by raw_DMS_directionality), but it should (always) be positive with the processed DMS scores. We will look into it and fix as needed.

Kind regards,
Pascal

**Comment by pascalnotin** [comment]
Hi Roshan,
Just made available slightly updated files addressing the directionality issue (available via the same download link).
Could you please let me know whether that addresses the issue?
Best,
Pascal

**Comment by pascalnotin** [comment]
@rmrao - I am closing the issue as I believe it is now resolved, but feel free to re-open if any issues with the latest version uploaded.
Best,
Pascal

**Comment by rmrao** [comment]
Ah, thanks pascal! Went on vacation right after this and forgot to check back on this issue. Thanks for the quick turnaround!
